/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://lgotx7q2gzgmplbprtjppw6m7a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jrk6oyzy3fgi7owmmtfx7y2aey",
    "aws_cognito_identity_pool_id": "us-east-2:797ee323-9463-48b3-8318-5b45a06e810a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PmlO9EEOo",
    "aws_user_pools_web_client_id": "3le9l0petaaut247vjc0v2boc5",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
